"""

Test data structure

Initialize UM types object with common data.
"""


from .data import (
    ACTION,
    ADMIN,
    APP_SM_DEFAULT_BASIC_SCOPE_2,
    APP_SM_DEFAULT_NON_BASIC_SCOPE_3,
    APP_SM_NON_DEFAULT_NON_BASIC_SCOPE_1,
    IDP_LDAP_CONFIG_1,
    IDP_LDAP_CONFIG_2,
    IDP_LOCAL_CONFIG,
    INTERNAL_ACTION,
    INTERNAL_ADMIN,
    INTERNAL_ADMIN_SCOPE,
    LDAP_CONFIG,
    MIX_SCOPE,
    NEW_INTERNAL_USER,
    NEW_SCOPE,
    NEW_USER,
    NEW_USER_LDAP,
    NEW_USR_NON_DEFAULT_NON_BASIC_SCOPE_6,
    OLD_SCOPE,
    OLD_USR_NON_DEFAULT_NON_BASIC_SCOPE_5,
    password,
    PMF_API_DESCRIPTOR,
    PMF_DEFAULT_BASIC_SCOPE_0,
    SM_API_DESCRIPTOR,
    TEST_SCOPE,
    USR_DEFAULT_BASIC_SCOPE_4
)

__all__ = [
    "ACTION",
    "ADMIN",
    "APP_SM_DEFAULT_BASIC_SCOPE_2",
    "APP_SM_DEFAULT_NON_BASIC_SCOPE_3",
    "APP_SM_NON_DEFAULT_NON_BASIC_SCOPE_1",
    "IDP_LDAP_CONFIG_1",
    "IDP_LDAP_CONFIG_2",
    "IDP_LOCAL_CONFIG",
    "INTERNAL_ACTION",
    "INTERNAL_ADMIN",
    "INTERNAL_ADMIN_SCOPE",
    "LDAP_CONFIG",
    "MIX_SCOPE",
    "NEW_INTERNAL_USER",
    "NEW_SCOPE",
    "NEW_USER",
    "NEW_USER_LDAP",
    "NEW_USR_NON_DEFAULT_NON_BASIC_SCOPE_6",
    "OLD_SCOPE",
    "OLD_USR_NON_DEFAULT_NON_BASIC_SCOPE_5",
    "password",
    "PMF_API_DESCRIPTOR",
    "PMF_DEFAULT_BASIC_SCOPE_0",
    "SM_API_DESCRIPTOR",
    "TEST_SCOPE",
    "USR_DEFAULT_BASIC_SCOPE_4"
]
