[tox]
envlist = test
skipsdist = True

[testenv:reqs]
# specific stage to build requirements
basepython = python3.11
deps =
    pip-tools~=7.4
passenv = *
setenv =
    INDEX_URL = {env:ATEME_NEXUS_PYPI_PROD_URL:https://nexus-rennes.ateme.net/repository/pypi-prod/simple}
    EXTRA_INDEX_URL = {env:ATEME_NEXUS_PYPI_DEV_URL:https://nexus-rennes.ateme.net/repository/pypi-dev/simple}
commands =
    # Backend reqs
    pip-compile {posargs} --index-url {env:INDEX_URL} --extra-index-url {env:EXTRA_INDEX_URL} --output-file=requirements.txt pyproject.toml
    pip-compile {posargs} --index-url {env:INDEX_URL} --extra-index-url {env:EXTRA_INDEX_URL} --extra tests --output-file=requirements-tests.txt pyproject.toml
    pip-compile {posargs} --index-url {env:INDEX_URL} --extra-index-url {env:EXTRA_INDEX_URL} --extra docs --output-file=requirements-dochtml.txt pyproject.toml
    pip-compile {posargs} --index-url {env:INDEX_URL} --extra-index-url {env:EXTRA_INDEX_URL} --output-file requirements-mypy.txt --extra=mypy pyproject.toml

[testenv:doc]
# Specific stage to build html documentation
basepython = python3.11
allowlist_externals=apt-get
setenv =
    DOC_OUTPUT_DIR = {env:TOX_DOC_OUTPUT_DIR:./documentation}
    PYTHONPATH = {toxinidir}:{toxinidir}../client:{env:PYTHONPATH:}
commands =
    apt-get update
    apt-get install -y libxmlsec1-dev pkg-config
    pip install -rrequirements-dochtml.txt
    pdoc3 --force --html --output-dir {env:DOC_OUTPUT_DIR} ateme/um_backend

[testenv:doc-api]
# Specific stage to build html API documentation
basepython = python3.11
deps =
    -rrequirements.txt
setenv =
    DOC_OUTPUT_DIR = {env:TOX_DOC_OUTPUT_DIR:./api-documentation}
commands =
    mkdir -p {env:DOC_OUTPUT_DIR}
    python -m ateme.openapi release ateme/um_backend/api/api.yaml {env:DOC_OUTPUT_DIR}/index.html

[testenv:lint]
basepython = python3.11
deps =
    pip >= 24.0
    -rrequirements-tests.txt
    pylint~=3.1
setenv =
    PYLINTRC = {env:PYLINTRC:"./pyproject.toml"}
    SOURCE_PATH = {env:SOURCE_PATH:ateme/um_backend tests }
    PYTHONPATH = {toxinidir}:{toxinidir}/../client:{env:PYTHONPATH:}
commands =
    pylint -j 2 --rcfile={env:PYLINTRC} --output-format=text {env:SOURCE_PATH}

[testenv:mypy]
basepython = python3.11
deps =
    pip >= 24.0
    -rrequirements-mypy.txt
setenv =
    MYPYINI = {env:MYPYINI:"./pyproject.toml"}
    SOURCE_PATH = {env:SOURCE_PATH:ateme}
commands =
    - mypy {env:SOURCE_PATH} --config-file {env:MYPYINI} --pretty --install-types --non-interactive --explicit-package-bases {posargs}

[testenv:test]
basepython = python3.11
deps =
    -rrequirements-tests.txt
setenv =
    DATABASE_HOST = {env:DATABASE_HOST:}
    LDAP_HOST = {env:LDAP_HOST:localhost}
    DOCKER_HOST = {env:DOCKER_HOST:}
    USER = {env:USER:}
    BUILD_NUMBER = {env:BUILD_NUMBER:}
    ATEME_HUB_RELEASE_USR = {env:ATEME_HUB_RELEASE_USR:}
    ATEME_HUB_RELEASE_PWD = {env:ATEME_HUB_RELEASE_PWD:}
    MAX_NUMBER_FAILED_CLIENT_LOGINS = 5
    PYTHONPATH = {toxinidir}:{toxinidir}/../client:{env:PYTHONPATH:}
commands =
   pytest {posargs:-sv --cov=ateme.um_backend}


[testenv:scripts]
# specific stage to use scripts
basepython = python3.11
deps =
    -rrequirements.txt
commands =
    - pip install -e .
    - {posargs}
