apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-pre-upgrade-serviceaccount
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app.kubernetes.io/component: pre-upgrade-job
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # Here we set the Helm Hook on "pre-upgrade" to execute on an upgrade request
    # after templates are rendered, but before any resources are loaded into Kubernetes
    "helm.sh/hook": pre-upgrade
    # We can delete the hook after the hook is successfully executed, if the hook failed during execution 
    # and delete the previous hook before the new hook is launched
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    # Add weight in order to create service account before job
    "helm.sh/hook-weight": "-5"
automountServiceAccountToken: false
