{{- if and .Values.authcontroller.enabled .Values.authcontroller.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "um.authcontroller.clusterRoleName" . | trim }}
  labels:
    release: {{ .Release.Name }}
    app.kubernetes.io/component: auth-controller
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  {{- with .Values.authcontroller.clusterRole.basicRules }}
  {{ toYaml . | nindent 2 | trim}}
  {{- end }}
  {{- with .Values.authcontroller.clusterRole.additionalRules }}
  {{ toYaml . | nindent 2 | trim }}
  {{- end }}
{{- end }}
