[tox]
envlist = run
skipsdist = True

[testenv:reqs]
basepython = python3.7
deps =
    pip-tools==6.14.0
setenv =
    INDEX_URL = {env:ATEME_NEXUS_PYPI_PROD_URL:https://nexus-rennes.ateme.net/repository/pypi-prod/simple}
    EXTRA_INDEX_URL = {env:ATEME_NEXUS_PYPI_DEV_URL:https://nexus-rennes.ateme.net/repository/pypi-dev/simple}
commands =
    pip-compile {posargs} --index-url {env:INDEX_URL} --extra-index-url {env:EXTRA_INDEX_URL} --output-file=requirements.txt requirements.in
    pip-compile {posargs} --index-url {env:INDEX_URL} --extra-index-url {env:EXTRA_INDEX_URL} --output-file=requirements-compile.txt requirements-compile.in
    pip-compile {posargs} --index-url {env:INDEX_URL} --extra-index-url {env:EXTRA_INDEX_URL} --output-file=requirements-tests.txt requirements-tests.in

[testenv:tests]
basepython = python3.7
deps =
    -rrequirements-tests.txt
commands =
    pytest ./tests/test_backup_restore.py {posargs}

[testenv:run]
basepython = python3.7
deps =
    -rrequirements.txt
commands =
    python generate_um_export_from_pms.py {posargs}

[testenv:lint]
basepython = python3.7
deps =
    pylint
    -rrequirements.txt
commands =
    pylint {posargs} ./generate_um_export_from_pms.py

[testenv:compile]
basepython = python3.7
deps =
    -rrequirements-compile.txt
commands =
    python -m nuitka \
        --onefile \
        --standalone \
        ./generate_um_export_from_pms.py \
        --include-plugin-directory=.tox/compile/lib/python3.7/site-packages/requests \
        --include-plugin-directory=.tox/compile/lib/python3.7/site-packages/urllib3 \
        --include-plugin-directory=.tox/compile/lib/python3.7/site-packages/Crypto \
        --include-plugin-directory=.tox/compile/lib/python3.7/site-packages/dns \
        {posargs}
