{{- if and .Values.database.certificate.enabled .Values.database.certificate.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.certificate.secretName }}
  labels:
    release: {{ .Release.Name }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ .Values.database.certificate.name }}: |
    {{ .Values.database.certificate.data | trim }}
{{- end }}