export const REFRESH_TOKEN = 'API.REFRESH_TOKEN'
export const TOKEN_INTROSPECTION = 'API.TOKEN_INTROSPECTION'
export const CHANGE_TOKEN_EXPIRATION = 'API.CHANGE_TOKEN_EXPIRATION'
export default {
  REFRESH_TOKEN,
  TOKEN_INTROSPECTION,
  CHANGE_TOKEN_EXPIRATION
}
